SELECT
  WUT.SEQ_WORK_USER_MT_ID
  , WUT.SEQ_REGULAR_WORK_MT_ID
  , RWT.BEGIN_HOUR
  , RWT.BEGIN_MINUTE
  , RWT.END_HOUR
  , RWT.END_MINUTE
FROM
  WORK_USER_MT WUT
  , REGULAR_WORK_MT RWT
WHERE
  WUT.SEQ_WORK_USER_MT_ID = (
    SELECT
      MAX(SEQ_WORK_USER_MT_ID)
    FROM
      WORK_USER_MT
    WHERE
      SEQ_LOGIN_ID = /* seqLoginId */2
  )
  AND
  RWT.SEQ_REGULAR_WORK_MT_ID = WUT.SEQ_REGULAR_WORK_MT_ID
