SELECT
  WUM.SEQ_REGULAR_WORK_MT_ID
  , WUM.SEQ_LOGIN_ID
  , WUM.SEQ_REGULAR_WORK_MT_ID
  , RWM.BEGIN_HOUR
  , RWM.BEGIN_MINUTE
  , RWM.END_HOUR
  , RWM.END_MINUTE
FROM
  -- 勤怠ユーザマスタ
  WORK_USER_MT WUM
  -- 定時情報マスタ
  , REGULAR_WORK_MT RWM
WHERE
  WUM.SEQ_WORK_USER_MT_ID = RWM.SEQ_REGULAR_WORK_MT_ID;


--SELECT
--  WUM.SEQ_REGULAR_WORK_MT_ID
--  , WUM.SEQ_LOGIN_ID
--  , WUM.SEQ_REGULAR_WORK_MT_ID
--  , RWM.BEGIN_HOUR
--  , RWM.BEGIN_MINUTE
--  , RWM.END_HOUR
--  , RWM.END_MINUTE
--FROM
--  WORK_USER_MT WUM
--  LEFT OUTER JOIN REGULAR_WORK_MT RWM
--    ON WUM.SEQ_WORK_USER_MT_ID = RWM.SEQ_REGULAR_WORK_MT_ID