-- ログインユーザ情報
DROP TABLE IF EXISTS LOGIN_USER_DATA;
-- メールユーザ情報
DROP TABLE IF EXISTS MAIL_USER_DATA;
-- 定時情報マスタ
DROP TABLE IF EXISTS REGULAR_WORK_MT;
-- 勤怠ユーザマスタ
DROP TABLE IF EXISTS WORK_USER_MT;
-- 日別勤怠登録情報
DROP TABLE IF EXISTS DAILY_WORK_ENTRY_DATA;
-- 営業日マスタ
DROP TABLE IF EXISTS BUSINESS_CALENDAR_MT;