-- ほげ
CREATE TABLE IF NOT EXISTS HOGE (
  -- シーケンスID
  ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'シーケンスID',
  -- 名前
  NAME VARCHAR(1000) COMMENT '名前',
  -- 日付
  DATE TIMESTAMP COMMENT '日付'
);