-- ログインユーザ情報
CREATE TABLE IF NOT EXISTS LOGIN_USER_DATA (
  -- ログインID
  SEQ_LOGIN_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'ログインID',
  -- パスワード
  PASSWORD VARCHAR(64) NOT NULL COMMENT 'パスワード',
  -- パスワード有効期限
  PASSWORD_EXPIRE DATE NOT NULL COMMENT 'パスワード有効期限',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE TIMESTAMP NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE TIMESTAMP NOT NULL COMMENT '更新日時'
);

-- メールユーザ情報
CREATE TABLE IF NOT EXISTS MAIL_USER_DATA (
  -- メールユーザID
  SEQ_MAIL_USER_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'メールユーザID',
  -- ログインID
  SEQ_LOGIN_ID INT NOT NULL COMMENT 'ログインID',
  -- メールアドレス
  MAIL_ADDRESS VARBINARY(1024) NOT NULL COMMENT 'メールアドレス',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE TIMESTAMP NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE TIMESTAMP NOT NULL COMMENT '更新日時'
);

-- 定時情報マスタ
CREATE TABLE IF NOT EXISTS REGULAR_WORK_MT (
  -- 定時情報マスタID
  SEQ_REGULAR_WORK_MT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '定時情報マスタID',
  -- 始業時間(時)
  BEGIN_HOUR INT NOT NULL COMMENT '始業時間(時)',
  -- 始業時間(分)
  BEGIN_MINUTE INT NOT NULL COMMENT '始業時間(分)',
  -- 終業時間(時)
  END_HOUR INT NOT NULL COMMENT '終業時間(時)',
  -- 終業時間(分)
  END_MINUTE INT NOT NULL COMMENT '終業時間(分)',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE TIMESTAMP NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE TIMESTAMP NOT NULL COMMENT '更新日時'
);

-- 勤怠ユーザマスタ
CREATE TABLE IF NOT EXISTS WORK_USER_MT (
  -- 勤怠ユーザマスタID
  SEQ_WORK_USER_MT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '勤怠ユーザマスタID',
  -- ログインID
  SEQ_LOGIN_ID INT NOT NULL COMMENT 'ログインID',
  -- 定時情報マスタID
  SEQ_REGULAR_WORK_MT_ID INT NOT NULL COMMENT '定時情報マスタID',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE TIMESTAMP NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE TIMESTAMP NOT NULL COMMENT '更新日時'
);

-- 日別勤怠登録情報
CREATE TABLE IF NOT EXISTS DAILY_WORK_ENTRY_DATA (
  -- 日別勤怠登録情報ID
  SEQ_DAILY_WORK_ENTRY_DATA_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '日別勤怠登録情報ID',
  -- 勤怠ユーザマスタID
  SEQ_WORK_USER_MT_ID INT NOT NULL COMMENT '勤怠ユーザマスタID',
  -- 勤怠日
  WORK_DATE DATE NOT NULL COMMENT '勤怠日',
  -- 始業時間(時)
  BEGIN_HOUR INT NOT NULL COMMENT '始業時間(時)',
  -- 始業時間(分)
  BEGIN_MINUTE INT NOT NULL COMMENT '始業時間(分)',
  -- 終業時間(時)
  END_HOUR INT NOT NULL COMMENT '終業時間(時)',
  -- 終業時間(分)
  END_MINUTE INT NOT NULL COMMENT '終業時間(分)',
  -- 承認ステータス
  STATUS VARCHAR(2) NOT NULL COMMENT '承認ステータス',
  -- 備考
  NOTE VARCHAR(256) COMMENT '備考',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE TIMESTAMP NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE TIMESTAMP NOT NULL COMMENT '更新日時'
);
