-- ログインユーザ情報
SHOW COLUMNS FROM LOGIN_USER_DATA;
-- メールユーザ情報
SHOW COLUMNS FROM MAIL_USER_DATA;
-- 定時情報マスタ
SHOW COLUMNS FROM REGULAR_WORK_MT;
-- 勤怠ユーザマスタ
SHOW COLUMNS FROM WORK_USER_MT;
-- 日別勤怠登録情報
SHOW COLUMNS FROM DAILY_WORK_ENTRY_DATA;